### ISSUE TITLE
Collaborator request for the project :)

### ISSUE THREAD

**Issue by goxr3plus** [badarshahzad/Jfx-Browser#60]
### Why i would like to have Collaborator Access ?
Hello  @badarshahzad  , i have a suggestion for your team . I would like you to add me as a collaborator to your project so i can publish releases and generally upgrade this repository.

### What permissions a collaborator has ?
https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

### How you can do it ?
You can go on https://github.com/badarshahzad/Jfx-Browser , settings -> collaborators -> type my name ( goxr3plus ) and add me .

### Finally 
If you would like to do it , i would be very glad :) . You can remove me any time you want because you are the admin .

### Can't you publish releases on your own fork ? 
No as far as i know because it is just a fork , so i have to copy all the code from your project and make a new repository with the same code and name . Though people must come to your repository not my own ... you know what i mean.

**Comment by badarshahzad** [comment]
Hi,
    We are happy to add you as a collaborator as you are spending your precious time in this project. 

> Welcome to Paloos Group :wave:  :smile: 

@naeemkhan12  @Hassankhan2015 @Shoaibkhan786 @RamzanShahidkhan @sanaullah786 
Cheers!

Badar

**Comment by RamzanShahidkhan** [comment]
Glad to hear your sound and your interest to contribute in team project.
Good luck.

**Comment by naeemkhan12** [comment]
sure why not :+1:

**Comment by goxr3plus** [comment]
OK now I will make it the best JavaFX Browser ever.

**Comment by Hassankhan2015** [comment]
Thanks so much




Thanks Stay Blessed.



Mohammad Hassan Iqbal Khan.
UOB# 14031263
Namal College Mianwali,
An Associate College of University of Bradford.

**Comment by naeemkhan12** [comment]
hope it would be fun to work with you 🍦 
![giphy](https://user-images.githubusercontent.com/15648371/33255561-16b7f348-d370-11e7-8d81-5cabdf7dc6d7.gif)
