### ISSUE TITLE
Support to gradle build

### ISSUE THREAD

**Issue by badarshahzad** [badarshahzad/Jfx-Browser#64]
I am creating new branch `gradle-branch` on which I'm trying to add gradle build support as the traffic is increasing so I think we should have to add each flavor for manual jar importing, maven and gradle.

@naeemkhan12  Can you create new branch `eclipse-branch` and get reset back to eclipse working project.
@goxr3plus  Can you create your new branch for `maven-branch` and mantain your dependance according to that.
In the mean while I'm adding the gradle build support  :+1:

**Comment by naeemkhan12** [comment]
will do :+1:

**Comment by badarshahzad** [comment]
:wave:  Gradle support has been added
![giphy-tumblr](https://user-images.githubusercontent.com/19945367/33391335-7af2de86-d55a-11e7-8a09-dd99500f873a.gif)
